defaults:
  - override /hydra/sweeper: optuna

name: "ggponc_ellipses"
wandb_project: ${name}

data:
  cnf_tsv_path: 'data/ellipses/ggponc_ellipses_compounds.tsv'
  controls_tsv_path: 'data/ellipses/ggponc_no_ellipses_small.tsv'
  ggponc_plain_text: 'data/ggponc_v2/plain_text/tokens/all_files_tokens'

# Training args

random_seed: 42

model_name: "google/mt5-base"
num_epochs: 10
generation_max_length: 277
length_multiplier: 1.5
train_batch_size: 8
eval_batch_size: 8
warmup_steps: 100
learning_rate : 5e-04
weight_decay: 1e-04
fp16: False
gradient_checkpointing: False

metrics:
  - exact_match
  - google_bleu

output_base_path: ./outputs/${name}

date_run: ${name}/${now:%Y-%m-%d_%H-%M-%S}

hydra:
  run:
    dir: ${output_base_path}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ./multirun/${name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    study_name: hyperparameter_search
    n_jobs: 1
    direction: maximize
    n_trials: 25

    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 12345
      n_startup_trials: 10

    params:
      learning_rate: interval(1e-06, 1e-01)
      train_batch_size: choice(4, 8, 16)
      weight_decay: interval(0.0, 1.0)
      warmup_steps: range(0, 100)
